# Generated by Django 4.2.13 on 2024-07-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_master',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('role_name', models.CharField(max_length=20)),
            ],
        ),
    ]
